<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <AssemblyTitle>AssetStudioMod by aelurum</AssemblyTitle>
        <AssemblyName>AssetStudioModCLI</AssemblyName>
        <Version>0.19.0.0</Version>
        <Copyright>Copyright © Perfare; Copyright © aelurum 2023-2025</Copyright>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AssetStudioUtility\AssetStudioUtility.csproj" />
        <ProjectReference Include="..\AssetStudio\AssetStudio.csproj" />
    </ItemGroup>

    <Target Name="CopyExtraFiles" AfterTargets="AfterBuild">
        <Message Text="Copying windows extra files for $(TargetFramework)... " Importance="high" />
        <Copy SourceFiles="$(SolutionDir)AssetStudioGUI\Libraries\libfbxsdk.dll" DestinationFolder="$(TargetDir)" ContinueOnError="false" />
        <Copy SourceFiles="$(SolutionDir)AssetStudioFBXNative\bin\x64\$(Configuration)\AssetStudioFBXNative.dll" DestinationFolder="$(TargetDir)" ContinueOnError="false" />
        <Copy SourceFiles="$(SolutionDir)Texture2DDecoderNative\bin\x64\$(Configuration)\Texture2DDecoderNative.dll" DestinationFolder="$(TargetDir)" ContinueOnError="false" />
        <Copy SourceFiles="$(ProjectDir)Libraries\win-x64\fmod.dll" DestinationFolder="$(TargetDir)" ContinueOnError="false" />
        <Copy SourceFiles="$(ProjectDir)Libraries\win-x64\ooz.dll" DestinationFolder="$(TargetDir)" ContinueOnError="false" />
    </Target>

</Project>
